### ISSUE TITLE
Jansi error on AARCH64

### ISSUE THREAD

**Issue by madmobhunter** [2lstudios-mc/FlamePaper#18]
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi64- in java.library.path, no jansi- in java.library.path, no jansi in java.library.path, /tmp/libjansi-64--7634490658782375848.so: /tmp/libjansi-64--7634490658782375848.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]
at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
at org.bukkit.craftbukkit.Main.main(Main.java:173)

Worked fine until patch c804f70.

**Comment by linsaftw** [comment]
fixed on 2a5099a

**Comment by madmobhunter** [comment]
Thank you for such a fast reply and update. I am excited to be a part of this community! Still getting:

java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi64- in java.library.path, no jansi- in java.library.path, no jansi in java.library.path, /tmp/libjansi-64--6168299318634776822.so: /tmp/libjansi-64--6168299318634776822.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]
at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
at org.bukkit.craftbukkit.Main.main(Main.java:173)

on server start with 2a5099a. It runs fine on my (brand new) windows pc. But when i put it onto my: 
ARM running Ubuntu Server 20.10 with java 8 
i get this error. Worked flawless until patch c804f70. I can get into discord and help you debug it if needed.

**Comment by linsaftw** [comment]
Does it happen on other spigot/paper versions? We tested on Debian, Ubuntu and Windows and works fine.

**Comment by madmobhunter** [comment]
Works fine with all other spigot version i have tested. Also works fine with 4926195. 
I read that versions of Jansi below 2.x do not have support for aarch64.

**Comment by linsaftw** [comment]
> Works fine with all other spigot version i have tested. Also works fine with [4926195](https://github.com/2lstudios-mc/FlamePaper/commit/4926195e8fce559dd951242e20f2437a8d1b42de). I read that versions of Jansi below 2.0 do not have support for aarch64. [GlowstoneMC/Glowstone#839](https://github.com/GlowstoneMC/Glowstone/issues/839) [fusesource/jansi#65](https://github.com/fusesource/jansi/pull/65)

I am sorry for you, this seems to be out of our hands. We will try our best to find and fix the issue :)

**Comment by madmobhunter** [comment]
IT WAS A BIT HACKY BUT I was able to get it to work by changing the new version of jansi you use to the old one from 4926195. Not sure why the newer one does not support ARM.

**Comment by madmobhunter** [comment]
what version of jansi are you using?

**Comment by linsaftw** [comment]
> what version of jansi are you using?

I think this is considered by other of the dependencies, we have to keep everything up to date to keep stability and performance. I think we can't do anything about this. You may need to ask jansi for support.

**Comment by madmobhunter** [comment]
I downloaded the latest version jansi-2.1.0 from: 

http://fusesource.github.io/jansi/download.html

you are not using the latest version.
works fine when i run with the latest version of jansi.

**Comment by madmobhunter** [comment]
I highly recommend you update your jansi to version 2.1.0

You can get it from:
http://fusesource.github.io/jansi/download.html

It has a lot of performance and bug fixes that everyone is missing out on.
I am running it right now on my ARM flawless.

**Comment by linsaftw** [comment]
> I highly recommend you update your jansi to version 2.1.0
> 
> You can get it from: http://fusesource.github.io/jansi/download.html
> 
> It has a lot of performance and bug fixes that everyone is missing out on. I am running it right now on my ARM flawless.

We don't have jansi in our dependencies; I think this is added by another dependency and not from us. I will have to investigate this further.

**Comment by linsaftw** [comment]
hi, please try latest release :) (updated jansi on 2f3145506aed1d69e878f9fec29d11eb67757b8c)

**Comment by madmobhunter** [comment]
that fixed it thank you so much!
